### PR TITLE
Fixed generic code paths by disabling non-VLAs

### PR DESCRIPTION
**Pull request by hfp**
This passes as before while preserving the previous changes except for toggling-in VLAs (toggled lines can be found by "`#if 0 /* TODO: no VLAs */`").

### CODE REVIEW

**Comment by alheinecke** [comment]
please remove scratch 7/8/9 and move back to stack allocations

+#if 0 /* TODO: no VLAs */
 element_input_type *const del_input_scratch_padding = (element_input_type*)(((char*)handle->scratch7) + ltid * LIBXSMM_UP2(scratch7_size * sizeof(element_input_type), LIBXSMM_CACHELINE));
+#else
+element_input_type del_input_scratch_padding[scratch7_size];
+#endif

Not sure what the todo means, it needs to stay scratch allocated

**Comment by hfp** [comment]
That's the case.

**Comment by hfp** [comment]
https://github.com/egeor/libxsmm/pull/21/commits/4428dae14bff4b893aa842ff35812df4bf493311

**Comment by alheinecke** [comment]
Why is then the Todo there?

**Comment by alheinecke** [comment]
Please get rid of the scratch7/8/9 stuff in handle, we want to have it simply as stack allocations

**Comment by hfp** [comment]
The TODO is about implementing non-VLAs. right now we have VLAs back.

**Comment by alheinecke** [comment]
But we cleanup the handle before merging, as we don't need that stuff, e.g handle->scratch7 and so on.

**Pull request merged**
